/*
This script is auto generated by UIELayoutCodeGenWindow

Copyright 2023 SUISUISHOU(blightue@gmail.com)

Licensed under the Apache License, Version 2.0 (the "License")
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using UnityEditor.UIElements;
using UnityEngine.UIElements;
using SuiSuiShou.UIEEx;

namespace SuiSuiShou.UIEEx.Editor
{
    public static partial class EditorUIELayout 
    {
///<summary>
///<para>
///PropertyField constructor.
///</para>
///</summary>
///<param name="parent">The parent of this element.</param>
        public static PropertyField PropertyField (VisualElement parent = null)
        {{
            PropertyField propertyField = new PropertyField();
            propertyField.SetParent(parent);
            return propertyField;
        }}

///<summary>
///<para>
///PropertyField constructor.
///</para>
///</summary>
///<param name="property">Providing a SerializedProperty in the construct just sets the bindingPath. You will still have to call Bind() on the PropertyField afterwards.</param>
///<param name="parent">The parent of this element.</param>
        public static PropertyField PropertyField (UnityEditor.SerializedProperty property, VisualElement parent = null)
        {{
            PropertyField propertyField = new PropertyField(property);
            propertyField.SetParent(parent);
            return propertyField;
        }}

///<summary>
///<para>
///PropertyField constructor.
///</para>
///</summary>
///<param name="property">Providing a SerializedProperty in the construct just sets the bindingPath. You will still have to call Bind() on the PropertyField afterwards.</param>
///<param name="label">Optionally overwrite the property label.</param>
///<param name="parent">The parent of this element.</param>
        public static PropertyField PropertyField (UnityEditor.SerializedProperty property, System.String label, VisualElement parent = null)
        {{
            PropertyField propertyField = new PropertyField(property, label);
            propertyField.SetParent(parent);
            return propertyField;
        }}

    }
}