/*
This script is auto generated by UIELayoutCodeGenWindow

Copyright 2023 SUISUISHOU(blightue@gmail.com)

Licensed under the Apache License, Version 2.0 (the "License")
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using UnityEngine.UIElements;
using SuiSuiShou.UIEEx;

namespace SuiSuiShou.UIEEx
{
    public static partial class UIELayout 
    {
///<summary>
///<para>
///Constructor.
///</para>
///</summary>
///<param name="parent">The parent of this element.</param>
        public static RepeatButton RepeatButton (VisualElement parent = null)
        {{
            RepeatButton repeatButton = new RepeatButton();
            repeatButton.SetParent(parent);
            return repeatButton;
        }}

///<summary>
///<para>
///Constructor.
///</para>
///</summary>
///<param name="clickEvent">The action to execute when the button is pressed.</param>
///<param name="delay">The initial delay before the action is executed for the first time.</param>
///<param name="interval">The interval between each execution of the action.</param>
///<param name="parent">The parent of this element.</param>
        public static RepeatButton RepeatButton (System.Action clickEvent, System.Int64 delay, System.Int64 interval, VisualElement parent = null)
        {{
            RepeatButton repeatButton = new RepeatButton(clickEvent, delay, interval);
            repeatButton.SetParent(parent);
            return repeatButton;
        }}

    }
}