/*
This script is auto generated by UIELayoutCodeGenWindow

Copyright 2023 SUISUISHOU(blightue@gmail.com)

Licensed under the Apache License, Version 2.0 (the "License")
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using UnityEngine.UIElements;
using SuiSuiShou.UIEEx;

namespace SuiSuiShou.UIEEx
{
    public static partial class UIELayout 
    {
///<summary>
///<para>
///Constructor.
///</para>
///</summary>
///<param name="parent">The parent of this element.</param>
        public static Slider Slider (VisualElement parent = null)
        {{
            Slider slider = new Slider();
            slider.SetParent(parent);
            return slider;
        }}

///<summary>
///<para>
///Constructor.
///</para>
///</summary>
///<param name="start"></param>
///<param name="end"></param>
///<param name="direction"></param>
///<param name="pageSize"></param>
///<param name="parent">The parent of this element.</param>
        public static Slider Slider (System.Single start, System.Single end, UnityEngine.UIElements.SliderDirection direction, System.Single pageSize, VisualElement parent = null)
        {{
            Slider slider = new Slider(start, end, direction, pageSize);
            slider.SetParent(parent);
            return slider;
        }}

///<summary>
///<para>
///Constructor.
///</para>
///</summary>
///<param name="label"></param>
///<param name="start"></param>
///<param name="end"></param>
///<param name="direction"></param>
///<param name="pageSize"></param>
///<param name="parent">The parent of this element.</param>
        public static Slider Slider (System.String label, System.Single start, System.Single end, UnityEngine.UIElements.SliderDirection direction, System.Single pageSize, VisualElement parent = null)
        {{
            Slider slider = new Slider(label, start, end, direction, pageSize);
            slider.SetParent(parent);
            return slider;
        }}

    }
}