/*
This script is auto generated by UIELayoutCodeGenWindow

Licensed under the Apache License, Version 2.0 (the "License")
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using UnityEditor.UIElements;
using UnityEngine.UIElements;
using SuiSuiShou.UIEEx;

namespace SuiSuiShou.UIEEx.Editor
{
    public static partial class EditorUIELayout 
    {
        public static GradientField GradientField (VisualElement parent = null)
        {
            GradientField gradientField = new GradientField();
            gradientField.SetParent(parent);
            return gradientField;
        }

        public static GradientField GradientField (System.String label, VisualElement parent = null)
        {
            GradientField gradientField = new GradientField(label);
            gradientField.SetParent(parent);
            return gradientField;
        }

    }
}