/*
This script is auto generated by UIELayoutCodeGenWindow

Copyright 2023 SUISUISHOU(blightue@gmail.com)

Licensed under the Apache License, Version 2.0 (the "License")
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using UnityEditor.UIElements;
using UnityEngine.UIElements;
using SuiSuiShou.UIEEx;

namespace SuiSuiShou.UIEEx.Editor
{
    public static partial class EditorUIELayout 
    {
        public static MaskField MaskField (System.Collections.Generic.List<System.String> choices, System.Int32 defaultMask, System.Func<System.String,System.String> formatSelectedValueCallback, System.Func<System.String,System.String> formatListItemCallback, VisualElement parent = null)
        {
            MaskField maskField = new MaskField(choices, defaultMask, formatSelectedValueCallback, formatListItemCallback);
            maskField.SetParent(parent);
            return maskField;
        }

        public static MaskField MaskField (System.String label, System.Collections.Generic.List<System.String> choices, System.Int32 defaultMask, System.Func<System.String,System.String> formatSelectedValueCallback, System.Func<System.String,System.String> formatListItemCallback, VisualElement parent = null)
        {
            MaskField maskField = new MaskField(label, choices, defaultMask, formatSelectedValueCallback, formatListItemCallback);
            maskField.SetParent(parent);
            return maskField;
        }

        public static MaskField MaskField (VisualElement parent = null)
        {
            MaskField maskField = new MaskField();
            maskField.SetParent(parent);
            return maskField;
        }

        public static MaskField MaskField (System.String label, VisualElement parent = null)
        {
            MaskField maskField = new MaskField(label);
            maskField.SetParent(parent);
            return maskField;
        }

    }
}