/*
This script is auto generated by UIELayoutCodeGenWindow

Copyright 2023 SUISUISHOU(blightue@gmail.com)

Licensed under the Apache License, Version 2.0 (the "License")
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using UnityEngine.UIElements;
using SuiSuiShou.UIEEx;

namespace SuiSuiShou.UIEEx
{
    public static partial class UIELayout 
    {
///<summary>
///<para>
///Construct a DropdownField.
///</para>
///</summary>
///<param name="parent">The parent of this element.</param>
        public static DropdownField DropdownField (VisualElement parent = null)
        {{
            DropdownField dropdownField = new DropdownField();
            dropdownField.SetParent(parent);
            return dropdownField;
        }}

///<summary>
///<para>
///Construct a DropdownField.
///</para>
///</summary>
///<param name="label"></param>
///<param name="parent">The parent of this element.</param>
        public static DropdownField DropdownField (System.String label, VisualElement parent = null)
        {{
            DropdownField dropdownField = new DropdownField(label);
            dropdownField.SetParent(parent);
            return dropdownField;
        }}

///<summary>
///<para>
///Construct a DropdownField.
///</para>
///</summary>
///<param name="choices"></param>
///<param name="defaultValue"></param>
///<param name="formatSelectedValueCallback"></param>
///<param name="formatListItemCallback"></param>
///<param name="parent">The parent of this element.</param>
        public static DropdownField DropdownField (System.Collections.Generic.List<System.String> choices, System.String defaultValue, System.Func<System.String,System.String> formatSelectedValueCallback, System.Func<System.String,System.String> formatListItemCallback, VisualElement parent = null)
        {{
            DropdownField dropdownField = new DropdownField(choices, defaultValue, formatSelectedValueCallback, formatListItemCallback);
            dropdownField.SetParent(parent);
            return dropdownField;
        }}

///<summary>
///<para>
///Construct a DropdownField.
///</para>
///</summary>
///<param name="label"></param>
///<param name="choices"></param>
///<param name="defaultValue"></param>
///<param name="formatSelectedValueCallback"></param>
///<param name="formatListItemCallback"></param>
///<param name="parent">The parent of this element.</param>
        public static DropdownField DropdownField (System.String label, System.Collections.Generic.List<System.String> choices, System.String defaultValue, System.Func<System.String,System.String> formatSelectedValueCallback, System.Func<System.String,System.String> formatListItemCallback, VisualElement parent = null)
        {{
            DropdownField dropdownField = new DropdownField(label, choices, defaultValue, formatSelectedValueCallback, formatListItemCallback);
            dropdownField.SetParent(parent);
            return dropdownField;
        }}

///<summary>
///<para>
///Construct a DropdownField.
///</para>
///</summary>
///<param name="choices"></param>
///<param name="defaultIndex"></param>
///<param name="formatSelectedValueCallback"></param>
///<param name="formatListItemCallback"></param>
///<param name="parent">The parent of this element.</param>
        public static DropdownField DropdownField (System.Collections.Generic.List<System.String> choices, System.Int32 defaultIndex, System.Func<System.String,System.String> formatSelectedValueCallback, System.Func<System.String,System.String> formatListItemCallback, VisualElement parent = null)
        {{
            DropdownField dropdownField = new DropdownField(choices, defaultIndex, formatSelectedValueCallback, formatListItemCallback);
            dropdownField.SetParent(parent);
            return dropdownField;
        }}

///<summary>
///<para>
///Construct a DropdownField.
///</para>
///</summary>
///<param name="label"></param>
///<param name="choices"></param>
///<param name="defaultIndex"></param>
///<param name="formatSelectedValueCallback"></param>
///<param name="formatListItemCallback"></param>
///<param name="parent">The parent of this element.</param>
        public static DropdownField DropdownField (System.String label, System.Collections.Generic.List<System.String> choices, System.Int32 defaultIndex, System.Func<System.String,System.String> formatSelectedValueCallback, System.Func<System.String,System.String> formatListItemCallback, VisualElement parent = null)
        {{
            DropdownField dropdownField = new DropdownField(label, choices, defaultIndex, formatSelectedValueCallback, formatListItemCallback);
            dropdownField.SetParent(parent);
            return dropdownField;
        }}

    }
}