/*
This script is auto generated by UIELayoutCodeGenWindow

Copyright 2023 SUISUISHOU(blightue@gmail.com)

Licensed under the Apache License, Version 2.0 (the "License")
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using UnityEngine.UIElements;
using SuiSuiShou.UIEEx;

namespace SuiSuiShou.UIEEx
{
    public static partial class UIELayout 
    {
///<summary>
///<para>
///Constructor.
///</para>
///</summary>
///<param name="parent">The parent of this element.</param>
        public static MinMaxSlider MinMaxSlider (VisualElement parent = null)
        {{
            MinMaxSlider minMaxSlider = new MinMaxSlider();
            minMaxSlider.SetParent(parent);
            return minMaxSlider;
        }}

///<summary>
///<para>
///Constructor.
///</para>
///</summary>
///<param name="minValue">The minimum value in the range to be represented.</param>
///<param name="maxValue">The maximum value in the range to be represented.</param>
///<param name="minLimit">The minimum value of the slider limit.</param>
///<param name="maxLimit">The maximum value of the slider limit.</param>
///<param name="parent">The parent of this element.</param>
        public static MinMaxSlider MinMaxSlider (System.Single minValue, System.Single maxValue, System.Single minLimit, System.Single maxLimit, VisualElement parent = null)
        {{
            MinMaxSlider minMaxSlider = new MinMaxSlider(minValue, maxValue, minLimit, maxLimit);
            minMaxSlider.SetParent(parent);
            return minMaxSlider;
        }}

///<summary>
///<para>
///Constructor.
///</para>
///</summary>
///<param name="minValue">The minimum value in the range to be represented.</param>
///<param name="maxValue">The maximum value in the range to be represented.</param>
///<param name="minLimit">The minimum value of the slider limit.</param>
///<param name="maxLimit">The maximum value of the slider limit.</param>
///<param name="label"></param>
///<param name="parent">The parent of this element.</param>
        public static MinMaxSlider MinMaxSlider (System.String label, System.Single minValue, System.Single maxValue, System.Single minLimit, System.Single maxLimit, VisualElement parent = null)
        {{
            MinMaxSlider minMaxSlider = new MinMaxSlider(label, minValue, maxValue, minLimit, maxLimit);
            minMaxSlider.SetParent(parent);
            return minMaxSlider;
        }}

    }
}